cart/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

food_cart/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    url(r'^admin/', admin.site.urls),
    #url(r'^chef/', admin.site.urls),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^orders/', include('orders.urls', namespace='orders')),
    url(r'^manager/', include('manager.urls', namespace='manager')),
    url(r'^', include('food_carts.urls', namespace="food_carts")),
    url(r'^accounts/', include('registration.backends.hmac.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

food_carts/urls.py
from django.conf.urls import url
from django.conf.urls import url, include
from . import views

urlpatterns = [

    url(r'^$', views.product_list, name='product_list'),
        url(r'^accounts/', include('registration.backends.hmac.urls')),


    url(r'^(?P<category_slug>[-\w]+)/$', views.product_list, name='product_list_by_category'),

    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.product_detail, name='product_detail'),

]

orders/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'create/$', views.order_create, name='orders_create'),
]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]

class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(
                        choices=PRODUCT_QUANTITY_CHOICES,
                        coerce= int
                        )
    update = forms.BooleanField(required=False,
                                initial=False,
                                widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from food_carts.models import Product
from .cart import Cart
from .forms import CartAddProductForm

# Create your views here.

@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)

    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product = product,
                 quantity = cd['quantity'],
                 update_quantity = cd['update'])

        return redirect('cart:cart_detail')

def cart_remove(request, product_id):
    cart = Cart(request)
    product=get_object_or_404(Product, id = product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')

def cart_detail(request):
    cart = Cart(request)

    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(
                        initial = {'quantity':item['quantity'],
                                   'update':True}
                        )
    return render(request, 'cart/detail.html', {'cart' : cart})

templates/cart/detail.html
{% extends "food_carts/base.html" %}
{% load staticfiles %}

{% block title %}
    Shopping Cart
{% endblock %}

{% block content %}
    <h1 id="title">Your Shopping Cart</h1>
    <div class="table-responsive">
        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>Image</th>
                    <th>Product</th>
                    <th>Quantity</th>
                    <th>Remove</th>
                    <th>Unit Price</th>
                    <th>Price</th>
                </tr>
            </thead>
            <tbody>
                {% for item in cart %}
                    {% with product=item.product %}
                        <tr>
                            <td>
                                <a href="{{ product.get_absolute_url }}">
                                    <img src="{% if product.image %}{{ product.image.url}}{% else %}{% static "img/no_image.png" %}{% endif %}" width="100" height="50">
                                </a>
                            </td>
                            <td>{{ product.name }}</td>
                            <td> &nbsp {{ item.quantity }}
                                <form action="{% url "cart:cart_add" product.id %}" method="post">
                                    {{ item.update_quantity_form.quantity }}
                                    {{ item.update_quantity_form.update }}
                                    <input type="submit" value="Update">
                                    {% csrf_token %}
                                </form>
                            </td>
                            <td><a href="{% url "cart:cart_remove" product.id %}"><button type="button" class="btn btn-danger">Remove</button></a> </td>
                            <td class="num">₹ {{ item.price }}</td>
                            <td class="num">₹ {{ item.total_price }}</td>
                        </tr>
                    {% endwith %}
                {% endfor %}
                <tr class="total">
                    <td>Total</td>
                    <td colspan="4"></td>
                    <td class="num">₹ {{ cart.get_total_price }}</td>
                </tr>
            </tbody>
        </table>
    </div>
    <p class="cart_options">
        <a href="{% url "food_carts:product_list" %}" class="buttonlight"><button type="button" class="btn btn-default">Continue Shopping</button></a>
        <a href="{% url 'orders:orders_create' %}" class="button"><button type="button" class="btn btn-default">Checkout</button></a>
    </p>
{% endblock %}