cart/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

food_cart/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    url(r'^admin/', admin.site.urls),
    #url(r'^chef/', admin.site.urls),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^orders/', include('orders.urls', namespace='orders')),
    url(r'^manager/', include('manager.urls', namespace='manager')),
    url(r'^', include('food_carts.urls', namespace="food_carts")),
    url(r'^accounts/', include('registration.backends.hmac.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

food_carts/urls.py
from django.conf.urls import url
from django.conf.urls import url, include
from . import views

urlpatterns = [

    url(r'^$', views.product_list, name='product_list'),
        url(r'^accounts/', include('registration.backends.hmac.urls')),


    url(r'^(?P<category_slug>[-\w]+)/$', views.product_list, name='product_list_by_category'),

    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.product_detail, name='product_detail'),

]

food_carts/models.py
from django.db import models
from django.core.urlresolvers import reverse

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=100, db_index=True)

    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('food_carts:product_list_by_category', args=[
            self.slug
        ])

class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products')
    name = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=100, db_index=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.PositiveIntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)

    index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return  reverse('food_carts:product_detail', args=[
            self.id,
            self.slug
        ])



'''
class Product(models.Model):
    CATEGORY = (
        ('DR', 'Drinks'),
        ('FF', 'Fast Foods'),
        ('SN', 'Snacks'),
        ('SD', 'Salads')
    )

    p_id = models.AutoField(primary_key=True)
    p_name = models.CharField(max_length=100)
    p_price = models.IntegerField()
    p_description = models.TextField()
    p_pics = models.CharField(max_length=250)
    p_category = models.CharField(max_length=4, choices=CATEGORY)
    slug = model

class User(models.Model):
    user_id = models.IntegerField()
    user_name = models.CharField(max_length=100)


class Inventiory(models.Model):
    p_id = models.OneToOneField(Product)
    amount_in_stock = models.IntegerField()

class Sales(models.Model):

    MOP = (
        ('CC', 'Credit Card'),
        ('DC', 'Debit Card'),
        ('MP', 'M-Pesa')
    )

    CH = (
        ('TR', 'True'),
        ('FL', 'False')
    )

    p_id = models.ManyToManyField(Product)
    user_id = models.ManyToManyField(User)
    no_bought = models.IntegerField()
    amount_paid = models.IntegerField()
    means_of_payment = models.CharField(max_length=10, choices=MOP)
    location = models.CharField(max_length=100)
    deliverd = models.CharField(max_length=2, choices=CH)

class Cart(models.Model):
    cart_id = models.AutoField(primary_key=True)
    user_id = models.ForeignKey(User)
    p_id = models.OneToOneField(Product)
    amount = models.IntegerField()
'''

food_carts/views.py
from django.shortcuts import render, get_object_or_404
from cart.forms import CartAddProductForm
from .models import *

# Create your views here.

def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)

    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)

    return render(request,
            'food_carts/products/list.html',
            {'category': category,
            'categories': categories,
            'products': products})

def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    cart_product_form = CartAddProductForm()

    return render(request,
                'food_carts/products/detail.html',
                {'product': product,
                 'cart_product_form' : cart_product_form})

templates/food_carts/base.html
{% load staticfiles %}

{% load crispy_forms_tags %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}OrganoKart{% endblock %}</title>
    <link href='https://fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'>
    <link href="{% static 'food_carts/bootstrap/css/bootstrap.css' %}" type="text/css" rel="stylesheet">
    <link href="{% static 'food_carts/bootstrap/css/bootstrap-theme.css' %}" type="text/css" rel="stylesheet">
    <link href="{% static 'food_carts/styles.css' %}" type="text/css" rel="stylesheet">
    <script src="{% static 'food_carts/jquery.js' %}" ></script>
    <script src="{% static 'food_carts/bootstrap/js/bootstrap.min.js' %}" ></script>
</head>
<body>
    <div class="container-fluid">
  <nav class="navbar navbar-default">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/" class="logo">OrganoKart</a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
         {% if categories %}
        <ul class="nav navbar-nav">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Category<span class="caret"></span></a>
              <ul class="dropdown-menu">
                  <li {% if not category %} class="selected" {% endif %}>
                      <a href="{% url "food_carts:product_list" %}">ALL</a>
                  </li>
                  {% for c in categories %}
                      <li {% if category.slug == c.slug %} class="selected" {% endif %}>
                          <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
                      </li>
                  {% endfor %}
              </ul>
          </li>
        </ul>
        {% endif %}
    <div id="subheader" class="nav navbar-nav navbar-center" style="padding: 15px;">
    
    

    </div>    
    <div id="subheader" class="nav navbar-nav navbar-right" style="padding: 15px;">
        <div class="cart">
            {% with total_items=cart|length %}
                {% if cart|length > 0 %}
                    Your Cart:
                    <a href="{% url 'cart:cart_detail' %}">
                    {{ total_items }} item{{ total_items|pluralize }},
                    ₹ {{ cart.get_total_price }}
                    </a>
                    {% else %}
                    Your cart is empty.
                {% endif %}
            {% endwith %}
        </div>
        </div><!-- /.navbar-collapse -->
    </div>
    </nav>
    <div id="content">
        {% block content %}
        {% endblock %}
    </div>
    </div>
</body>
</html>